<?php
?>

<p>PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY! PLEASE PAY ATTENTION TO PROVISIONS THAT EXCLUDE OR LIMIT LIABILITY AND TERMS OF GOVERNING LAW AND JURISDICTION, WHICH MAY APPEAR IN CAPITAL LETTERS.</p>
