<?php

return [
  'showAdminPanel' =>'0',
  'adminUserChoosing' =>'0',
  'choose_receiving_point' => '1',
  'country' => [
    'Canada',
    'China',
    'United States',
    'Angola',
    'Argentina',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Belgium',
    'Benin',
    'Bolivia',
    'Bonaire',
    'Bosnia-Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Cambodia',
    'Cameroon',
    'Chile',
    'Colombia',
    'Costa Rica',
    'Croatia',
    'Curacao',
    'Cyprus',
    'Czech Republic',
    'Democratic Republic of Congo',
    'Denmark',
    'East Africa',
    'Ecuador',
    'El Salvador',
    'El Salvador-San Miguel',
    'Estonia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Germany',
    'Ghana',
    'Great Britain',
    'Greece',
    'Guadaloupe',
    'Guatemala',
    'Honduras',
    'Honduras-Tegucigalpa',
    'Hong Kong',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Ireland',
    'Israel',
    'Italy',
    'Ivory Coast',
    'Japan',
    'Kazakhstan',
    'Korea',
    'Kosovo',
    'Kuwait',
    'Latvia',
    'Lesotho',
    'Lithuania',
    'Luxembourg',
    'Macau',
    'Macedonia',
    'Malaysia',
    'Martinique',
    'Mauritania',
    'Mexico',
    'Moldova',
    'Namibia',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Nigeria',
    'Northern Ireland',
    'Norway',
    'Panama',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Republic of Congo',
    'Reunion Islands',
    'Romania',
    'Russia',
    'Rwanda',
    'Saba',
    'Samoa',
    'Saudi Arabia',
    'Senegal',
    'Serbia & Montenegro',
    'Singapore',
    'Slovak Republic',
    'Slovenia',
    'South Africa',
    'Spain',
    'St. Eustatius',
    'St. Maarten',
    'Suriname',
    'Swaziland',
    'Sweden',
    'Switzerland',
    'Taiwan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Turkey',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'Uruguay',
    'Venezuela',
    'Vietnam',
  ],
  'ShippingCarrier'=>[
    'ups'=>"UPS",
    'usps'=>'usps',
    'fedex'=>'FedEx Ground or FedEx Home Delivery',
    'canadapost'=>'canadapost'
  ],
  'package_source_list'=>[
    0=>"manual",
    1=>"eBay"
  ],
];
