<?php

return [
  'country' => [
    'Canada',
    'China',
    'United States',
    'Angola',
    'Argentina',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Belgium',
    'Benin',
    'Bolivia',
    'Bonaire',
    'Bosnia-Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Cambodia',
    'Cameroon',
    'Chile',
    'Colombia',
    'Costa Rica',
    'Croatia',
    'Curacao',
    'Cyprus',
    'Czech Republic',
    'Democratic Republic of Congo',
    'Denmark',
    'East Africa',
    'Ecuador',
    'El Salvador',
    'El Salvador-San Miguel',
    'Estonia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Germany',
    'Ghana',
    'Great Britain',
    'Greece',
    'Guadaloupe',
    'Guatemala',
    'Honduras',
    'Honduras-Tegucigalpa',
    'Hong Kong',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Ireland',
    'Israel',
    'Italy',
    'Ivory Coast',
    'Japan',
    'Kazakhstan',
    'Korea',
    'Kosovo',
    'Kuwait',
    'Latvia',
    'Lesotho',
    'Lithuania',
    'Luxembourg',
    'Macau',
    'Macedonia',
    'Malaysia',
    'Martinique',
    'Mauritania',
    'Mexico',
    'Moldova',
    'Namibia',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Nigeria',
    'Northern Ireland',
    'Norway',
    'Panama',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Republic of Congo',
    'Reunion Islands',
    'Romania',
    'Russia',
    'Rwanda',
    'Saba',
    'Samoa',
    'Saudi Arabia',
    'Senegal',
    'Serbia & Montenegro',
    'Singapore',
    'Slovak Republic',
    'Slovenia',
    'South Africa',
    'Spain',
    'St. Eustatius',
    'St. Maarten',
    'Suriname',
    'Swaziland',
    'Sweden',
    'Switzerland',
    'Taiwan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Turkey',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'Uruguay',
    'Venezuela',
    'Vietnam',
  ],
  'states' => [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'State',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
    'default',],
  'ShippingCarrier'=>[
    'ups'=>"UPS",
    'usps'=>'USPS',
    'fedex'=>'FedEx Ground or FedEx Home Delivery',
    'canadapost'=>'canadapost'
  ],
  'ShippingCarrierShort'=>[
    'ups'=>"UPS",
    'usps'=>'USPS',
    'fedex'=>'FedEx',
    'canadapost'=>'canadapost'
  ],
  'package_source_list'=>[
    0=>"manual",
    1=>"eBay"
  ],
  'pac_title'=>[
    2=>'Small parcel',
    10=>'Medium parcel',
    30=>'Large parcel',
    70=>'Extra Large parcel',
    100=>'Monster parcel'
  ]
];
