<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset;
use johnitvn\ajaxcrud\BulkButtonWidget;
use yii\widgets\Pjax;
use yii\bootstrap\ActiveForm;
use yii\widgets\DetailView;
use app\components\ParcelPrice;
use kartik\widgets\DatePicker;


/* @var $this yii\web\View */
/* @var $searchModel app\modules\orderInclude\models\OrderIncludeSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Order payment';
$this->params['breadcrumbs'][] = $this->title;


$submitOption = [
  'class' => 'btn btn-lg btn-success'
];

?>
<form id="w0" class=""  method="post">
<h4 class="modernui-neutral2">Order payment</h4>
  <?php
  foreach ($paces as $pac) {
    $tot_col=0;
    ?>
      <div class="col-md-5">
        <div class="pay_list padding-top-10 margin-top-10"><b>Package type : </b><span class="pull-right"><?=\Yii::$app->params['package_source_list'][$pac->source];?></span></div>
        <?php
        if($pac->track_number_type==0){
          ?>
          <div class="pay_list"><b>Track number </b>(generated by us) <b>:</b>
            <span class="pull-right">
              <?=strlen($pac->track_number)>3?$pac->track_number:'____';?>
            </span>
          </div>
          <?php
        }else {
          ?>
          <div class="pay_list"><b>Track number : </b><span class="pull-right"><?= $pac->track_number; ?></span></div>
          <?php
        }
        ?>
        <div class="pay_list"><b>Weight : </b><span class="pull-right"><?=number_format($pac->weight,2);?> lb</span></div>
      </div>

      <div class="col-md-12">
        <div class="col-md-3">
          <div class="pay_title"><b>_</b></div>
          <div class="pay_list2"><b>Price : </b></div>
          <div class="pay_list2"><b>PST : </b></div>
          <div class="pay_list2"><b>GST/HST : </b></div>
          <div class="pay_list4"><b>Total :</b></div>
        </div>

        <div class="col-md-2">
          <div class="pay_title"><b>По тарифу</b></div>
          <div class="pay_list2"><?=number_format($pac->price,2);?></div>
          <div class="pay_list2"><?=number_format($pac->qst,2);?></div>
          <div class="pay_list2"><?=number_format($pac->gst,2);?></div>
          <div class="pay_list4"><?=number_format($pac->price+$pac->gst+$pac->qst,2);?></div>
        </div>

        <?php
          $paySuccessful=$pac->getPaySuccessful();
          if($paySuccessful AND count($paySuccessful)>0){
            $tot_col++;
            ?>
            <div class="col-md-2">
              <div class="pay_title"><b>Оплаченно</b></div>
              <div class="pay_list2"><?=number_format($paySuccessful[0]->price,2);?></div>
              <div class="pay_list2"><?=number_format($paySuccessful[0]->qst,2);?></div>
              <div class="pay_list2"><?=number_format($paySuccessful[0]->gst,2);?></div>
              <div class="pay_list4"><?=number_format($paySuccessful[0]->price+$paySuccessful[0]->gst+$paySuccessful[0]->qst,2);?></div>
            </div>
            <?php
          };

          //получаем данные о инвойсах
          $invoice=$pac->getTrackInvoice();
          if(!$invoice->getIsNewRecord()){
            $tot_col++;
            ?>
            <div class="col-md-2">
              <div class="pay_title"><b>Service fee</b></div>
              <div class="pay_list2"><?=number_format($invoice->price,2);?></div>
              <div class="pay_list2"><?=number_format($invoice->qst,2);?></div>
              <div class="pay_list2"><?=number_format($invoice->gst,2);?></div>
              <div class="pay_list4"><?=number_format($invoice->price+$invoice->gst+$invoice->qst,2);?></div>
            </div>

            <div class="col-md-2">
              <div class="pay_title"><b>Shipping fee</b></div>
              <div class="pay_list2"><?=number_format($invoice->dop_price,2);?></div>
              <div class="pay_list2"><?=number_format($invoice->dop_qst,2);?></div>
              <div class="pay_list2"><?=number_format($invoice->dop_gst,2);?></div>
              <div class="pay_list4"><?=number_format($invoice->dop_price+$invoice->dop_gst+$invoice->dop_qst,2);?></div>
            </div>
            <?php
            //получаем данные о уже осуществленных платежах
            $paySuccessful=$invoice->getPaySuccessful();
            if($paySuccessful AND count($paySuccessful)>0){
              ?>
              <div class="col-md-2">
                <div class="pay_title"><b>Оплаченно</b></div>
                <div class="pay_list2"><?=number_format($paySuccessful[0]->price,2);?></div>
                <div class="pay_list2"><?=number_format($paySuccessful[0]->qst,2);?></div>
                <div class="pay_list2"><?=number_format($paySuccessful[0]->gst,2);?></div>
                <div class="pay_list4"><?=number_format($paySuccessful[0]->price+$paySuccessful[0]->gst+$paySuccessful[0]->qst,2);?></div>
              </div>
              <?php
            };
          }

          if($tot_col>0){
            ?>
            <div class="col-md-2">
              <div class="pay_title"><b>total to pay</b></div>
              <div class="pay_list2"><?=number_format($pac->sub_total['price'],2);?></div>
              <div class="pay_list2"><?=number_format($pac->sub_total['qst'],2);?></div>
              <div class="pay_list2"><?=number_format($pac->sub_total['gst'],2);?></div>
              <div class="pay_list4"><?=number_format($pac->sub_total['sum'],2);?></div>
            </div>        
            <?php
          }
        ?>
      </div>
    <?php
    if($pac->sub_total['price']==0){
      ?>
      <h6 class="bg-success text-center fg-white padding-10">
        <span class="glyphicon glyphicon-ok-sign"></span> Pac paid
      </h6>
      <div class="paid_img"></div>
      <?php
      echo Html::hiddenInput('payment_type', -1, []);
    }else{
      ?>
      <h6 class="bg-warning text-center fg-white padding-10">
        <i class="icon-metro-warning"></i> Pac isn't paid yet
      </h6>
      <div class="notpaid_img"></div>
      <?php
      if(Yii::$app->user->identity->isManager()){
        ?>
        <div class="block_adm">
          <?= Html::checkbox('agree_'.$pac->id, false, [
            'label' => '<span class="fa fa-check otst"></span> Client has refused payment',
            'class'=>"hidden_block_communication",
            'sum'=>$pac->sub_total['sum'],
            'vat'=>$pac->sub_total['vat']
          ]);?>
          <div class="agree_<?=$pac->id;?> vertic" style="display: none;">
            <label>Please, enter the non-payment reason</label>
            <div class="row">
              <div class="col-md-12 full_width">
                <?= Html::textarea('text_not_agree_'.$pac->id, "",['class'=>'']); ?>
              </div>
            </div>
          </div>
        </div>
        <?php
      }
    }
  }
  ?>

  <hr class="podes">

  <?php
  if(!Yii::$app->user->identity->isManager()){?>
    <div class="col-md-offset-2 trans_text custom-radio">
      <?= Html::radioList('payment_type',null,
        [
          1 => "PayPal",
          2 => "I will pay at warehouse"
        ],[
          'item' => function($index, $label, $name, $checked, $value) {
            $return = '<label>';
            $return .= '<input type="radio" name="' . $name . '" value="' . $value . '" >';
            $return .= '<span></span>&nbsp;&nbsp;';
            $return .= ucwords($label);
            $return .= '</label><br>';
            return $return;
          }
        ]
      );
      ?>
    </div>
    <?php
  }?>

  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <?=Html::a('<i class="glyphicon glyphicon-chevron-left"></i> Back', ['/orderInclude/border-form/'.$order_id], ['class' => 'btn btn-default pull-left']) ?>
        <?php
        if(Yii::$app->user->identity->isManager()){
          echo Html::a('Return to orders list', ['/'], ['class' => 'btn btn-info pull-left margin-left-10']);
          if($paces[0]->status<2){
            //админ может принимать платеж и это необходимо сделать
            if(Yii::$app->user->can("takePay") && $total['price']>0){
              //админ может принимать посылки
              if(Yii::$app->user->can("takeParcel")){
                //принять посылку и оплату
                echo Html::submitButton('Customer paid order. Accept the order for the receiving point.', ['class' => 'btn btn-success pull-right']);
              }else{
                //принять деньги. Посылка остается у клиента.
                echo Html::submitButton('Customer paid order.', ['class' => 'btn btn-success pull-right']);
              }
            }else{
              //админ может принимать посылки
              if(Yii::$app->user->can("takeParcel")){
                //принять посылку. Все уже оплачено
                echo Html::submitButton('Accept the order for the receiving point.', ['class' => 'btn btn-success pull-right']);
              }
            }
          }else{
          }
        }else{
          echo Html::submitButton('Next <i class="glyphicon glyphicon-chevron-right"></i>', ['class' =>'btn btn-success pull-right']);
        }
        ?>
      </div>
    </div>
  </div>
</form>

<script>
  function vaidate_comment(){
    validate=true;
    els=$('.hidden_block_communication:checked');
    for (i=0;i<els.length;i++){
      el=$('[name=text_not_'+els.eq(i).attr('name')+"]");
      if(el.val().length<5){
        validate=false;
        show_err(el.parent(),'Field scale required');
        //Добписать валидацию
      }else{
        hide_err(el.parent());
      }
    }
    return validate;
  }

  $("form").on('submit',function(e){
    validate=vaidate_comment();
    if(!validate){
      gritterAdd('Error','For non-payment, you must specify the reason.','gritter-danger');
      e.preventDefault();
      return false;
    }

    return true;
  });

  $('[name^="text_not_agree_"]').keyup(function(){
    if(this.value.length>5){
      hide_err($(this).parent());
    }
  })
</script>
