<?php

namespace app\modules\address\models;

use Yii;

/**
 * This is the model class for table "new_address".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $first_name
 * @property string $last_name
 * @property string $company_name
 * @property string $adress_1
 * @property string $adress_2
 * @property integer $city
 * @property integer $address_type
 */
class Address extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'new_address';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['first_name', 'last_name', 'company_name', 'adress_1',
                'zip', 'phone', 'state', 'city', 'address_type'], 'required'],
            [['user_id', 'address_type'], 'integer'],
            [['first_name', 'city', 'last_name'], 'string', 'max' => 60],
            [['company_name'], 'string', 'max' => 128],
            [['adress_1', 'adress_2'], 'string', 'max' => 256],
            [['zip'], 'integer', 'min' => 10000],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'first_name' => 'First Name',
            'last_name' => 'Last Name',
            'company_name' => 'Company Name',
            'adress_1' => 'Adress 1',
            'adress_2' => 'Adress 2',
            'city' => 'City',
            'address_type' => 'Address Type',
        ];
    }

    public function beforeSave($insert)
    {
        $this->user_id = Yii::$app->user->id;
        if ($this->user_id == null) $this->user_id = -1;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
